theme: jekyll-theme-minimal

repository: HCLIMcom/HCLIMdoc

logo: /images/logo/HCLIM_logo_colour.png

docs_list_title: On this page
docs:
- title: Home 
  url: /

- title: About HCLIM
  children:
      - title: HCLIM consortium
        url: /about-hclim/consortium/
      - title: Technical description
        url: /about-hclim/technical-description/

- title: Research Areas
  children:
      - title: Regional downscaling
        url: /research-areas/regional-downscaling/
      - title: Coupling
        url: /research-areas/coupling/
      - title: High latitudes
        url: /research-areas/high-latitudes/
      - title: AI / Machine learning 
        url: /research-areas/ai/
      - title: Pseudo global warming 
        url: /research-areas/pgw/

- title: Projects
  url: /projects/

- title: News & Announcements
  url: /news/

- title: References
  url: /references/

collections:
  news:
    output: true
    permalink: /news/:name/