theme: jekyll-theme-minimal

repository: HCLIMcom/HCLIMdoc

logo: /images/logo/HCLIM_logo_colour.png

docs_list_title: On this page
docs:
- title: Home 
  url: /

- title: About HCLIM
    children:
      - title: Members
        url: /about-hclim/consortium/
      - title: History
        url: /about-hclim/technical-description/
        
- title: Members
  url: /members/

- title: News & Announcements
  url: /news/

- title: References
  url: /references/

collections:
  news:
    output: true
    permalink: /news/:name/