theme: jekyll-theme-minimal

repository: HCLIMcom/HCLIMdoc

logo: /images/logo/HCLIM_logo_colour.png

docs_list_title: On this page
docs:
- title: Home 
  url: /

- title: Members
  url: /members/

- title: News & Announcements
  url: /news/

- title: References
  url: /references/

collections:
  news:
    output: true
    permalink: /news/:name/